### ISSUE TITLE
Pop fails to load if var newBuild is null in focusedBuild function in model.js with error Uncaught TypeError: Cannot read property 'recentBuild' of null

### ISSUE THREAD

**Issue by quophyie** [alexaitken/circleci-monitor#12]
Pop fails to load if var ** `newBuild`** is null in function **`focusedBuild`** function in **`model.js`** with error **`Uncaught TypeError: Cannot read property 'recentBuild' of null`**

**Comment by alexaitken** [comment]
version 1.3.7 will now handle this situation.
