### ISSUE TITLE
Don't display green icon until whole workflow is finished

### ISSUE THREAD

**Issue by hubertjakubiak** [alexaitken/circleci-monitor#20]
I see green icon when just checkout code was finished successfully. I would expect branch name to be blue (running colour) all the time until whole workflow is finished.

**Comment by alexaitken** [comment]
The extension works by tracking the recent build status using this api `https://circleci.com/api/v1/projects`.   The extension does not use the workflow concept, it was developed before Circle Ci introduced workflows.  

I believe the extension will still work if each step of the workflow is a build. There is a chance that it will misreport the status if the query to the api falls between the completion of one job and the start of another.  
It is unclear to me how it would handle reporting the status if there are parallel builds.  

Can you provide more information about the data in this api call `https://circleci.com/api/v1/projects` when the extension is showing a the green icon too early?  Make sure to anonymize any private or secret information before posting.

**Comment by hubertjakubiak** [comment]
> There is a chance that it will misreport the status if the query to the api falls between the completion of one job and the start of another.

I believe that's the case. I can close this issue for now. It's not big problem for me, I can't reproduce it now, it happens very rarely.
